global:
  scrape_interval: 15s

scrape_configs:
  - job_name: gateway
    static_configs:
      - targets: ["gateway:8000"]
  - job_name: orchestrator
    static_configs:
      - targets: ["orchestrator:8001"]
  - job_name: library_retrieve_step
    static_configs:
      - targets: ["library-retrieve-step:8002"]
